spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/FORMFOSS
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 970308
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/Form
jwt:
  secret: my-secret-key
  header: Authorization
  start-pattern: 'formfoss '
  expiration: 604800
url:
  authentication: '/auth'
  public: '/public'
  frontend: '/#frontend'
