sudo: false
language: java
jdk:
- oraclejdk8
services:
  - mysql
script:
- test/run.sh
notifications:
  slack:
    secure: YP/zbxHBQu+HeC5GK9Rqu/p/c7rLwExDvV3RSTc6h3VViuYKQoCe/NCdhSlWqvK1KEmXfVDWxzmKYRYRZBUP4sxHCRHP0YSC32S+8Z3B5CauLEmv5Dbr9hHvYInuQRv4mmAtt/XS5drxy23gNLITWy2zydKuk8lVeX4SCaGLaxFqzjnsmFiViFihIf1Q2WiwVWU1iCzdpXksTYf4bdcYV5fFDQwn+ZeDq9+4owwdPeYBnyPmvy47tLGXuOo0ZWyJLM+Id0RBYmGdNj5IB5/HrkJs7kwrEUNrytm/9Xe0BwKf9hYAJb2jhik2yAf01AB25OsUkpFMiz+iRJkkizklY71i3BYSPJnko11/zZRUCxn8Flbh9/Sz1kukOygl0v0pKTifWxyFSHhmySJxBIx9gd377BU6Huq0hrFDqnA+zUJtCnLdCcexPtdnYxSPLudvt+ziFoKkSQirtnIkmqAJnuaHBtuDwTh+lrPY7ZaZChBgFQ+H9cyJB+DGBFeufOlaxSHskL2e6THYhf5f4+y3zy5DDZxb8twXtuj0ZubWf0yCyN1Ad9i70vfcF41CYFfUhmC4jWHH8ODDR2KzH8DU+pQv6iNJWMLR2FxYPJV7BYuVawttRYFyUmTUgxnkIQ4b9VHqDzyE3CuZF0HuOX4DXWhja3NyqtJQskLr0zRw+gg=
